services:
  postgres:
    image: postgres:16-alpine
    container_name: gym-tracker-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 256M

  app:
    build: .
    container_name: gym-tracker-app
    depends_on:
      - postgres
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://gym-tracker-db:5432/${DB_NAME}
        SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
        SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
        JAVA_OPTS: "-Xmx300m -Xms200m"
        JWT_SECRET: ${JWT_SECRET}
        JWT_EXPIRATION: ${JWT_EXPIRATION}
    ports:
      - "80:8080"
    deploy:
      resources:
        limits:
          memory: 450M

volumes:
  postgres_data:
