name: Java CI with Maven and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: gymtrackerdb
        ports:
          - 5432:5432
          
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

        

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/gymtrackerdb
        SPRING_DATASOURCE_USERNAME: admin
        SPRING_DATASOURCE_PASSWORD: admin
        # Just for test runs
        JWT_SECRET: "superrandomtoken"
        JWT_EXPIRATION: 3600000


    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: spring-boot-app-jar
        path: target/*.jar
        retention-days: 5

    - name: Build Docker image
      run: docker build -t my-app:${{ github.sha }} .
